### ISSUE TITLE
Missing training-data under resources

### ISSUE THREAD

**Issue by damianofalcioni** [Alexander-Nasuta/FAIRWork-Resource-Allocation-Demonstrator-using-NN#1]
Hi Alexander,
to test the functionalities of the [demonstrator_nn_v01.py](https://github.com/Alexander-Nasuta/FAIRWork-Resource-Allocation-Demonstrator-using-NN/blob/main/src/fairwork_rwth/demonstrator_ml/demonstrator_nn_v01.py) I need the `training-data` folder that is not available in the `resources` folder.
Could you please commit it?
Thanks

**Comment by Alexander-Nasuta** [comment]
Hi there,

Thank you for bringing this up, and I appreciate your interest in testing the functionalities of this repo. However, I'd like to clarify that it is generally considered a bad practice to use Git for tracking data in machine learning applications. Data files for machine learning can often be quite large and can quickly exceed the file size limits imposed by platforms like GitHub.

To maintain good version control practices, we typically exclude data files from version control by explicitly listing them in the `.gitignore` file. This is why you couldn't find the `training-data` folder in the `resources` folder, as it's **intentionally left out**.

To assist with your testing, I have made some updates. I've extended the `README.md` file to include an example CSV and added two example data files to the folder `resources/example-training-data`. You can now use these example files to test the functionalities of `demonstrator_nn_v01.py`.
Alternatively, you can generate data for testing purposes using the `dummy_data_generator.py` script, which is available in the repository.

Best regards,
Alexander

**Comment by damianofalcioni** [comment]
Hi Alexander,
thanks for the clarification. Anyway in the `get_model` function I see that you initialize the `DemonstratorNeuralNet` with a dataset from the `training-data` folder. 
Is this required before loading the model at line 117 or can it be initialized without the training-data?
Thanks,
Damiano

**Comment by Alexander-Nasuta** [comment]
Hi,
You are absolutely correct concerning the initialization. The input and output sizes should be hardcoded here, avoiding any dependencies on the training data. I have accordingly updated the repository.

Best Regards,
Alexander
